/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package selegram;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.Box;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author SKings
 */
public class CreateGroupPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateGroupPanel
     */
    MainFrame mainFrame;
    Box listBox;
    String type;
    ArrayList<JCheckBox> checkBoxs;

    public CreateGroupPanel(MainFrame mainFrame, String type) {
        initComponents();
        this.mainFrame = mainFrame;
        this.type = type;
        customInit();
    }

    /**
     * programmer function
     */
    public void customInit() {
        create_create_btn.setText("Create " + type);
        listScrollpane.getVerticalScrollBar().setAutoscrolls(true);
        frien_panel.setLayout(new BorderLayout());
        listBox = Box.createVerticalBox();
        frien_panel.add(listBox, BorderLayout.NORTH);
        frien_panel.revalidate();
        frien_panel.repaint();
//        for (int i = 0; i < 25; i++) {
//            listBox.add(new JButton("saaaaaaaaaaaaaaaaaaaaaaaaaaaaaalaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaammmmmmmm"));
//        }
        checkBoxs = new ArrayList<>();
        ArrayList<Friend> friends = getFriends();
        for (int i = 0; i < friends.size(); i++) {
            JCheckBox jcb = new JCheckBox(friends.get(i).fusername);
            jcb.setFont(new Font("Calibri", 0, 18));
            jcb.setBackground(Color.white);
            jcb.setName("F" + friends.get(i).fchatid);
            checkBoxs.add(jcb);
            mainFrame.addToResultBox(frien_panel, listBox, jcb);
        }
    }

    public ArrayList<Friend> getFriends() {
        ArrayList<Friend> friends;
        ////hame friend ha inja ezafe she be in array list
        ////
        friends = mainFrame.user.getFriends();
//        friends.add(new Friend("akbar", "1"));
//        friends.add(new Friend("akbar", "1"));
//        friends.add(new Friend("akbar", "1"));
        return friends;
    }

    public ArrayList<Friend> selectedFriends() {
        ArrayList<Friend> friends = new ArrayList<>();
        ////
        ////
        for (int i = 0; i < checkBoxs.size(); i++) {
            if (checkBoxs.get(i).isSelected()) {
                friends.add(new Friend(checkBoxs.get(i).getText(), checkBoxs.get(i).getName().substring(1)));
            }
        }
        return friends;
    }

    public int groupCreated(String gname, ArrayList<Friend> participant) {
        JSONArray farr = new JSONArray();
        for(int i=0;i<participant.size();i++){
            farr.put(participant.get(i).fusername);
        }
        String command = "make_"+type;
        JSONObject obj = new JSONObject();
        obj.put("command", command).put("options", new JSONObject().put("name",create_name_txt.getText()).put("username", mainFrame.user.getUsername()).put("participants", farr));
        String result = mainFrame.clientHandler.getAnswer(obj.toString());
        JSONObject res = new JSONObject(result);
        if (res.get("status").toString().equalsIgnoreCase("ok")) {
            return 1;
        }
        return 0;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        create_name = new javax.swing.JLabel();
        create_name_txt = new javax.swing.JTextField();
        create_create_btn = new javax.swing.JButton();
        listScrollpane = new javax.swing.JScrollPane();
        frien_panel = new javax.swing.JPanel();
        create_cancel_btn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(700, 430));

        create_name.setBackground(new java.awt.Color(255, 255, 255));
        create_name.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        create_name.setForeground(new java.awt.Color(0, 0, 0));
        create_name.setText("Name: ");

        create_name_txt.setBackground(new java.awt.Color(255, 255, 255));
        create_name_txt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        create_name_txt.setForeground(new java.awt.Color(0, 0, 0));
        create_name_txt.setToolTipText("");
        create_name_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 167, 226)));
        create_name_txt.setCaretColor(new java.awt.Color(99, 137, 226));

        create_create_btn.setBackground(new java.awt.Color(47, 169, 226));
        create_create_btn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        create_create_btn.setForeground(new java.awt.Color(255, 255, 255));
        create_create_btn.setBorder(null);
        create_create_btn.setLabel("Create Group");
        create_create_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                create_create_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                create_create_btnMouseExited(evt);
            }
        });
        create_create_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_create_btnActionPerformed(evt);
            }
        });

        listScrollpane.setBackground(new java.awt.Color(255, 255, 255));
        listScrollpane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 137, 226)));
        listScrollpane.setPreferredSize(new Dimension(486,350));

        frien_panel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout frien_panelLayout = new javax.swing.GroupLayout(frien_panel);
        frien_panel.setLayout(frien_panelLayout);
        frien_panelLayout.setHorizontalGroup(
            frien_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );
        frien_panelLayout.setVerticalGroup(
            frien_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        listScrollpane.setViewportView(frien_panel);

        create_cancel_btn.setBackground(new java.awt.Color(47, 169, 226));
        create_cancel_btn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        create_cancel_btn.setForeground(new java.awt.Color(255, 255, 255));
        create_cancel_btn.setText("Cancel");
        create_cancel_btn.setBorder(null);
        create_cancel_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                create_cancel_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                create_cancel_btnMouseExited(evt);
            }
        });
        create_cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_cancel_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(create_name, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(create_create_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(create_name_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                .addGap(169, 169, 169))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(162, 162, 162)
                    .addComponent(listScrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(169, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(163, 163, 163)
                    .addComponent(create_cancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(459, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(create_name)
                    .addComponent(create_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 331, Short.MAX_VALUE)
                .addComponent(create_create_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addComponent(listScrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(73, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(376, Short.MAX_VALUE)
                    .addComponent(create_cancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void create_create_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_create_btnMouseEntered
        // TODO add your handling code here:
        create_create_btn.setBackground(new Color(37, 159, 216));
    }//GEN-LAST:event_create_create_btnMouseEntered

    private void create_create_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_create_btnMouseExited
        // TODO add your handling code here:
        create_create_btn.setBackground(new Color(47, 169, 226));
    }//GEN-LAST:event_create_create_btnMouseExited

    private void create_create_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_create_btnActionPerformed
        // TODO add your handling code here:
        if (!create_name_txt.getText().trim().isEmpty()) {
            ArrayList<Friend> fs = selectedFriends();
            if (fs.size() > 0) {
                int state = groupCreated(create_name_txt.getText().trim(), fs);
                if (state == 1) {
                    mainFrame.switchPanels(this, new MessagePanel(mainFrame));
                } else {
                    JOptionPane.showMessageDialog(mainFrame, "cant connect to server!!");
                }
            } else {
                JOptionPane.showMessageDialog(mainFrame, "No friend added!!");
            }
        } else {
            JOptionPane.showMessageDialog(mainFrame, "Name is Empty!!");
        }
    }//GEN-LAST:event_create_create_btnActionPerformed

    private void create_cancel_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_cancel_btnMouseEntered
        // TODO add your handling code here:
        create_cancel_btn.setBackground(new Color(37, 159, 216));
    }//GEN-LAST:event_create_cancel_btnMouseEntered

    private void create_cancel_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_cancel_btnMouseExited
        // TODO add your handling code here:
        create_cancel_btn.setBackground(new Color(47, 169, 226));
    }//GEN-LAST:event_create_cancel_btnMouseExited

    private void create_cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_cancel_btnActionPerformed
        // TODO add your handling code here:
        mainFrame.switchPanels(this, new profilePanel(mainFrame, mainFrame.user.getUsername()));
    }//GEN-LAST:event_create_cancel_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton create_cancel_btn;
    private javax.swing.JButton create_create_btn;
    private javax.swing.JLabel create_name;
    private javax.swing.JTextField create_name_txt;
    private javax.swing.JPanel frien_panel;
    private javax.swing.JScrollPane listScrollpane;
    // End of variables declaration//GEN-END:variables
}
