/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package selegram;

/**
 *
 * @author SKings
 */
public class MessageCloud extends javax.swing.JPanel {

    /**
     * Creates new form MessageCloud
     */
    public MessageCloud(String username, String text) {
        initComponents();
        cloud_username_lbl.setText(username);
        text = "<html>"+text+"</html>";
        text = text.replace("\n", "<br/>");
        cloud_main_lbl.setText(text);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cloud_username_lbl = new javax.swing.JLabel();
        cloud_main_lbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));

        cloud_username_lbl.setBackground(new java.awt.Color(255, 255, 255));
        cloud_username_lbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        cloud_username_lbl.setForeground(new java.awt.Color(97, 12, 157));
        cloud_username_lbl.setText("Username");

        cloud_main_lbl.setBackground(new java.awt.Color(255, 255, 255));
        cloud_main_lbl.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cloud_main_lbl.setForeground(new java.awt.Color(0, 0, 0));
        cloud_main_lbl.setText("Lorem ipsom");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cloud_username_lbl)
                        .addGap(0, 304, Short.MAX_VALUE))
                    .addComponent(cloud_main_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cloud_username_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cloud_main_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cloud_main_lbl;
    private javax.swing.JLabel cloud_username_lbl;
    // End of variables declaration//GEN-END:variables
}
